<?php

namespace AppBundle\Repository;

/**
 * Org_eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Org_eventRepository extends \Doctrine\ORM\EntityRepository
{
}
