<?php

namespace AppBundle\Repository;

/**
 * OrgEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgEventRepository extends \Doctrine\ORM\EntityRepository
{
}
