<?php

namespace AppBundle\Repository;

/**
 * Party_participant_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Party_participant_listRepository extends \Doctrine\ORM\EntityRepository
{
}
