<?php

namespace AppBundle\Repository;

/**
 * RegistrantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrantRepository extends \Doctrine\ORM\EntityRepository
{
}
